spring.application.name=Soo-Shinsa

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/soo_shinsa}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}

spring.mvc.hiddenmethod.filter.enabled=true

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:validate}
jwt.secret=${JWT_SECRET:please_change_this_secret_key}
jwt.expiry-millis=${JWT_ACCESS_TOKEN_EXPIRATION:3600000}
jwt.refresh-expiry-millis=${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

# ?? ?? ?? (Redis ?? ?? ???)
logging.level.org.springframework.cache=trace

cloud.aws.credentials.accessKey=${AWS_ACCESS_KEY:your_access_key}
cloud.aws.credentials.secretKey=${AWS_SECRET_KEY:your_secret_key}
cloud.aws.s3.region=${AWS_REGION:ap-northeast-2}
cloud.aws.s3.bucket=${AWS_S3_BUCKET:your-bucket}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

# UTF-8 \uC124\uC815
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4

jpa.properties.hibernate.auto_quote_keyword=true

# Spring Batch Job enable
spring.batch.job.enabled=true
spring.batch.jdbc.initialize-schema=${BATCH_INIT_SCHEMA:never}

spring.mvc.static-path-pattern=/**
spring.web.resources.static-locations=classpath:/static/

#mybatis
mybatis.mapper-locations=classpath:mappers/*.xml

springdoc.swagger-ui.oauth2-redirect-url=http://localhost:8080/callback
springdoc.swagger-ui.use-root-path=true


toss.secret_api_key=${TOSS_SECRET_KEY:test_sk_placeholder}
toss.client_api_key=${TOSS_CLIENT_KEY:test_ck_placeholder}
toss.success_url:${TOSS_ORIGIN_URL:http://localhost:8080}/api/v1/payments/toss/success
toss.fail_url:${TOSS_ORIGIN_URL:http://localhost:8080}/api/v1/payments/toss/fail
toss.base-url=https://api.tosspayments.com/v1

kakao.client_id=${KAKAO_CLIENT_ID:your_client_id}
kakao.redirect_uri=${KAKAO_REDIRECT_URI:http://localhost:8080/callback}
kakao.client_secret=${KAKAO_CLIENT_SECRET:your_client_secret}
kakao.token_uri=https://kauth.kakao.com/oauth/token
kakao.user_info_uri=https://kapi.kakao.com/v2/user/me

server.tomcat.max-threads=200
server.tomcat.max-connections=200
server.tomcat.keep-alive-timeout=60000
server.tomcat.connection-timeout=60000

# Actuator & Prometheus Metrics
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.tags.application=soo-shinsa


